### ISSUE TITLE
Create a test suite for testing inputs in a language agnostic manner

### ISSUE THREAD

**Issue by kvch** [elastic/elastic-agent-inputs#3]
The goal of this task is to provide a suite for testing inputs to validate that it can be controlled by Elastic Agent and can forward events to the shipper. The test suite should rely on the `testing` package of Golant.

### Requirements

* The tester must be able to test an input regardless of its language (e.g. input can be written in Python)
* The tester must check if the input understands the control protocol
* The tester must check if the input can ship events using the shipper protocol

#### Control protocol

* Reports OK if correct configuration is sent
* Reports Error if incorrect configuration is sent
* Can start with correct configuration
* Can be stopped when running in healthy state
* Can be killed if running in degraded state

#### Shipper

* Can publish events to the shipper
* Can handle publishing errors

**Comment by cmacknz** [comment]
Adding in a comment from a previous issue since I still like the idea:

Rather than a framework or a separate test suite an interesting idea would be to just build these tests and validation steps into the agent (and perhaps shipper) themselves.

We could have a command for the agent that determines whether some binary can be run by the agent for example and prints out a compatibility report.
